import { Category, Area, EmergencyContact } from '@/src/types';

export const STATIC_CATEGORIES: Category[] = [
  {
    id: 1,
    name_en: 'Doctors & Specialists',
    name_ur: 'ڈاکٹرز و سپیشلسٹس',
    slug: 'doctors',
    icon: 'Stethoscope',
    color: '#0D9488',
    sort_order: 1,
    businesses_count: 4,
  },
  {
    id: 2,
    name_en: 'Hospitals & Clinics',
    name_ur: 'ہسپتال و کلینکس',
    slug: 'hospitals',
    icon: 'Hospital',
    color: '#0284C7',
    sort_order: 2,
    businesses_count: 3,
  },
  {
    id: 3,
    name_en: 'Medical Stores & Pharmacies',
    name_ur: 'میڈیکل سٹورز اور فارمیسی',
    slug: 'medical-stores',
    icon: 'Pill',
    color: '#10B981',
    sort_order: 3,
    businesses_count: 2,
  },
  {
    id: 4,
    name_en: 'Schools & Colleges',
    name_ur: 'سکولز اور کالجز',
    slug: 'schools',
    icon: 'GraduationCap',
    color: '#8B5CF6',
    sort_order: 4,
    businesses_count: 2,
  },
  {
    id: 5,
    name_en: 'Restaurants & Cafes',
    name_ur: 'ریسٹورنٹس اور کیفے',
    slug: 'restaurants',
    icon: 'UtensilsCrossed',
    color: '#F59E0B',
    sort_order: 5,
    businesses_count: 3,
  },
  {
    id: 6,
    name_en: 'Mobile & Electronics',
    name_ur: 'موبائل اور الیکٹرانکس',
    slug: 'mobile-shops',
    icon: 'Smartphone',
    color: '#EC4899',
    sort_order: 6,
    businesses_count: 2,
  },
  {
    id: 7,
    name_en: 'Electricians & Technicians',
    name_ur: 'الیکٹریشنز اور ٹیکنیشنز',
    slug: 'electricians',
    icon: 'Zap',
    color: '#F97316',
    sort_order: 7,
    businesses_count: 2,
  },
  {
    id: 8,
    name_en: 'Plumbers & Sanitary',
    name_ur: 'پلمبرز اور سینیٹری',
    slug: 'plumbers',
    icon: 'Wrench',
    color: '#3B82F6',
    sort_order: 8,
    businesses_count: 1,
  },
  {
    id: 9,
    name_en: 'Banks & ATMs',
    name_ur: 'بینکس اور اے ٹی ایم',
    slug: 'banks',
    icon: 'Building2',
    color: '#6366F1',
    sort_order: 9,
    businesses_count: 2,
  },
  {
    id: 10,
    name_en: 'Hotels & Marquees',
    name_ur: 'ہوٹلز اور مارکیز',
    slug: 'hotels',
    icon: 'Hotel',
    color: '#14B8A6',
    sort_order: 10,
    businesses_count: 2,
  },
  {
    id: 11,
    name_en: 'Salons & Parlours',
    name_ur: 'سیلونز اور پارلرز',
    slug: 'salons',
    icon: 'Scissors',
    color: '#D946EF',
    sort_order: 11,
    businesses_count: 1,
  },
  {
    id: 12,
    name_en: 'Grocery & Supermarts',
    name_ur: 'گروسری اور سپر مارٹس',
    slug: 'grocery',
    icon: 'ShoppingCart',
    color: '#84CC16',
    sort_order: 12,
    businesses_count: 2,
  },
];

export const STATIC_AREAS: Area[] = [
  { id: 1, name_en: 'Katchery Road', name_ur: 'کچہری روڈ', slug: 'katchery-road', businesses_count: 3 },
  { id: 2, name_en: 'Rail Bazaar', name_ur: 'ریل بازار', slug: 'rail-bazaar', businesses_count: 4 },
  { id: 3, name_en: 'Allama Iqbal Road', name_ur: 'علامہ اقبال روڈ', slug: 'allama-iqbal-road', businesses_count: 3 },
  { id: 4, name_en: 'Club Road', name_ur: 'کلب روڈ', slug: 'club-road', businesses_count: 4 },
  { id: 5, name_en: 'Model Town', name_ur: 'ماڈل ٹاؤن', slug: 'model-town', businesses_count: 3 },
  { id: 6, name_en: 'Hospital Road', name_ur: 'ہسپتال روڈ', slug: 'hospital-road', businesses_count: 4 },
  { id: 7, name_en: 'Bypass / KLP Road', name_ur: 'بائی پاس / کے ایل پی روڈ', slug: 'bypass-klp-road', businesses_count: 3 },
  { id: 8, name_en: 'Grain Market', name_ur: 'غلہ منڈی', slug: 'grain-market', businesses_count: 1 },
];

export const EMERGENCY_CONTACTS: EmergencyContact[] = [
  {
    id: 'rescue1122',
    name_en: 'Rescue 1122 Emergency',
    name_ur: 'ریسکیو 1122 ایمرجنسی',
    phone: '1122',
    number: '1122',
    category: 'Emergency Rescue',
    sort_order: 1,
    is_active: true,
    description_en: 'Ambulance, fire rescue & disaster management',
    description_ur: 'ایمبولینس، آگ بجھانے اور ہنگامی امداد',
    icon: 'ShieldAlert',
    color: '#EF4444',
    badge: '24/7 Free',
  },
  {
    id: 'police15',
    name_en: 'Police Helpline 15',
    name_ur: 'پولیس ہیلپ لائن 15',
    phone: '15',
    number: '15',
    category: 'Law & Order',
    sort_order: 2,
    is_active: true,
    description_en: 'City police response & crime reporting',
    description_ur: 'شہری پولیس کنٹرول روم اور ہنگامی شکایت',
    icon: 'BadgeCheck',
    color: '#2563EB',
    badge: 'Emergency',
  },
  {
    id: 'fire16',
    name_en: 'Fire Brigade Sadiqabad',
    name_ur: 'فائر بریگیڈ صادق آباد',
    phone: '16',
    number: '16',
    category: 'Fire & Rescue',
    sort_order: 3,
    is_active: true,
    description_en: 'Municipal committee fire extinguishing unit',
    description_ur: 'میونسپل کمیٹی فائر بریگیڈ سروس',
    icon: 'Flame',
    color: '#F97316',
    badge: 'TMA Unit',
  },
  {
    id: 'edhi115',
    name_en: 'Edhi Ambulance Service',
    name_ur: 'ایدھی ایمبولینس سروس',
    phone: '115',
    number: '115',
    category: 'Medical & Relief',
    sort_order: 4,
    is_active: true,
    description_en: 'Non-profit 24-hour medical emergency ambulance',
    description_ur: 'ایدھی فاؤنڈیشن 24 گھنٹے ایمبولینس سروس',
    icon: 'HeartPulse',
    color: '#059669',
    badge: 'Emergency',
  },
];

export const POPULAR_SEARCH_TAGS = [
  { label_en: 'Doctors', label_ur: 'ڈاکٹرز', query: 'doctor' },
  { label_en: 'THQ Hospital', label_ur: 'ٹی ایچ کیو ہسپتال', query: 'thq' },
  { label_en: 'Pharmacies', label_ur: 'میڈیکل سٹور', query: 'pharmacy' },
  { label_en: 'Mutton Karahi', label_ur: 'کڑاہی', query: 'karahi' },
  { label_en: 'Plumbers', label_ur: 'پلمبر', query: 'plumber' },
  { label_en: 'Electricians', label_ur: 'الیکٹریشن', query: 'electric' },
  { label_en: 'Mobile Repair', label_ur: 'موبائل ریپئر', query: 'mobile' },
  { label_en: 'Wedding Marquees', label_ur: 'شادی ہال', query: 'marquee' },
  { label_en: 'Model Town', label_ur: 'ماڈل ٹاؤن', query: 'model town' },
];
